export const nameList = [
  "Aarav",
  "Aanya",
  "Amit",
  "Ananya",
  "Arjun",
  "Avani",
  "Chirag",
  "Divya",
  "Esha",
  "Gaurav",
  "Ishaan",
  "Jaya",
  "Kavya",
  "Laksh",
  "Meera",
  "Neha",
  "Omkar",
  "Pooja",
  "Rohan",
  "Sanya",
  "Tanvi",
  "Utkarsh",
  "Vaishnavi",
  "Yash",
  "Zara",
  "Aditya",
  "Bhavya",
  "Chetan",
  "Deeksha",
  "Eshita",
  "Farhan",
  "Gitanjali",
  "Harsh",
  "Ishita",
  "Jatin",
  "Kirti",
  "Lavanya",
  "Manan",
  "Nandini",
  "Ojas",
  "Prisha",
  "Rajat",
  "Saumya",
  "Tejas",
  "Uma",
  "Vishal",
  "Yamini",
  "Zainab",
];

export const randomMessages = [
  "Hello, how are you?",
  "Have a great day!",
  "Coding is fun!",
  "What's your favorite color?",
  "Stay positive!",
  "Learn something new today!",
  "Coffee is life!",
  "Keep smiling!",
  "Life is an adventure!",
  "Be kind to yourself.",
  "Embrace the challenges.",
  "Dream big, work hard.",
  "Explore the unknown.",
  "Believe in yourself.",
  "You've got this!",
  "Chase your dreams.",
  "Make it happen.",
  "Create your sunshine.",
  "Enjoy the journey.",
  "Find joy in the ordinary.",
  "Celebrate small victories.",
  "Seize the day!",
  "Do what you love.",
  "Stay curious.",
  "Make a difference.",
  "Be fearless.",
  "Be the change.",
  "Spread kindness.",
  "Life is short, smile often.",
  "Appreciate the little things.",
  "Strive for progress, not perfection.",
  "Stay focused and never give up.",
  "Inhale confidence, exhale doubt.",
  "You are capable of amazing things.",
  "Every moment is a fresh beginning.",
  "Follow your heart.",
  "Create your own sunshine.",
  "Leap, and the net will appear.",
  "The best is yet to come.",
  "Believe in the magic within you.",
  "Radiate positivity.",
  "Do more things that make you forget to check your phone.",
  "Be yourself; everyone else is already taken.",
  "Life is too important to be taken seriously.",
  "Keep calm and carry on.",
  "Don't worry, be happy!",
];
